spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  # この設定しておくとhtmlファイルがホットスワップされる
  thymeleaf:
    cache: false
    prefix: file:crewsync/src/main/resources/templates/
  # shema.sqlとdata.sqlをspring起動時に毎時実行したい場合はmode: alwaysに変更する
  sql:
    init:
      mode: never
logging:
  level:
    root: INFO
    # Spring Securityのログを出力したい場合: DEBUGに変更する
    org.springframework.security: OFF
  file:
    name: crewsync/logs/app.log
mybatis:
  mapper-locations: classpath:/com/example/crewsync/domains/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
debug: true
