name: Spring CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      TZ: ${{ secrets.TZ }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Make Gradle executable
      run: chmod +x ./api/crewsync/gradlew

    - name: Build with Gradle(Jacoco)
      run: ./api/crewsync/gradlew build jacocoTestReport

    - name: Archive unit test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-report
        path: build/reports/tests/test

    - name: Archive coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html
