name: Spring CI with Gradle

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Docker Compose
        run: |
          docker-compose up -d db
          docker-compose build api

      - name: Set executable permission for gradlew
        run: chmod +x ./crewsync/gradlew

      - name: Run tests
        run: docker-compose run api ./crewsync/gradlew test
